apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fuchicorp-wordpress-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-fuchicorp-prod
spec:
  rules:

  - host: fuchicorp.com
    http:
      paths:
      - backend:
          serviceName: fuchicorp-wordpress-service
          servicePort: {{ .Values.wordpress_service_port }}

  tls:
  - hosts:
    - fuchicorp.com
    secretName: workdpress-tls-prod
